version: '3.8'
services:
 db:
  container_name: todo-node-api-db
  image: postgres:latest
  restart: always
  environment: 
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
   POSTGRES_DB: postgres-users
  ports: 
   - "5432:5432"
 app:
  container_name: todo-node-api
  restart: always
  build: .
  ports: 
    - "5050:5050"
  depends_on: 
    - db